---
name: Lint Code Base

on: push

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Investigation 1
              run: ls -asl

            - name: Investigation 2
              run: ls -asl $GITHUB_WORKSPACE

            - name: Investigation 3
              run: pwd

            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: master
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PYTHON_BLACK_CONFIG_FILE: ../../../$GITHUB_WORKSPACE/pyproject.toml
                  PYTHON_ISORT_CONFIG_FILE: ./file-consolidator/pyproject.toml
